apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: myproject
  name: myproject
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myproject
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myproject
    spec:
      containers:
        image: 214758749246.dkr.ecr.us-west-2.amazonaws.com/github-action-demo
        imagePullPolicy: Always
        name: ponycar
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
